# Generated by Django 4.1.3 on 2023-11-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0002_mongomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MongoModel',
        ),
    ]
