# Generated by Django 4.1.3 on 2023-12-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0003_delete_mongomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
