# Generated by Django 4.1.3 on 2023-12-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0006_utilizador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='data_desativado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='encomendacliente',
            name='data_encomenda_cliente',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='faturacliente',
            name='data_emissao_fatura',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='guiaderemessa',
            name='data_saida_forn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notasdeencomenda',
            name='data_de_chegada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notasdeencomenda',
            name='data_de_envio',
            field=models.DateTimeField(null=True),
        ),
    ]
