# Generated by Adriano Valente do Vale on 2023-12-29 22:33

from django.db import migrations
from django.db import models



class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0008_fornecedor_email_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField('StockComponente', 'id_stock', models.AutoField(max_length=255)),
        migrations.AlterField('TipoDeEquipamento', 'id_tipo_de_equipamento', models.AutoField(max_length=255)),
        migrations.AlterField('TipoComponente', 'id_tipo_componente', models.AutoField(max_length=255)),
        migrations.AlterField('TipoDeMaoDeObra', 'id_tipo_mao_de_obra', models.AutoField(max_length=255))
    ]
