# Generated by Django 4.1.3 on 2024-01-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0009_auto_20231229_2233'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='stockcomponente',
        #     name='id_stock',
        #     field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='tipocomponente',
        #     name='id_tipo_componente',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='tipodeequipamento',
        #     name='id_tipo_de_equipamento',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='tipodemaodeobra',
        #     name='id_tipo_mao_de_obra',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
