# Generated by Adriano Valente do Vale on 2024-01-14 18:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0012_equipamento_nome_equipamento'),
    ]

    operations = [
        migrations.AlterField('Equipamento', 'stock_min_equip', models.IntegerField(null=True))
    ]
