# Generated by Django 4.1.3 on 2024-01-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0013_auto_20240114_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='tipodemaodeobra',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='TipoDeMaoDeObra_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.tipodemaodeobra'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='stock_min_equip',
            field=models.IntegerField(),
        ),
    ]
