# Generated by Django 4.1.3 on 2023-11-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_componente', models.CharField(max_length=256)),
                ('stock', models.IntegerField()),
                ('preco_compra', models.FloatField(null=True)),
                ('peso', models.FloatField(null=True)),
                ('caracteristicas', models.CharField(max_length=256, null=True)),
                ('margem_lucro', models.FloatField(null=True)),
                ('stock_min', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaCliente',
            fields=[
                ('id_encomenda_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('preco_enc_c', models.FloatField(null=True)),
                ('morada_armazem', models.CharField(max_length=256, null=True)),
                ('morada_cliente', models.CharField(max_length=256, null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('data_encomenda_cliente', models.DateField(null=True)),
                ('nome_artigo', models.CharField(max_length=256, null=True)),
                ('telemovel_cliente', models.CharField(max_length=256, null=True)),
                ('metodo_pagamento', models.CharField(max_length=256, null=True)),
                ('estado', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('preco_equipamento', models.FloatField()),
                ('preco_de_producao', models.FloatField()),
                ('stock_equip', models.IntegerField()),
                ('caracteristicas_equip', models.CharField(max_length=256, null=True)),
                ('margem_lucro_equip', models.IntegerField(null=True)),
                ('stock_min_equip', models.CharField(max_length=10, null=True)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.componente')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaCliente',
            fields=[
                ('id_fatura_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nif_loja', models.IntegerField(null=True)),
                ('nome_cliente', models.CharField(max_length=256, null=True)),
                ('nome_loja', models.CharField(max_length=256, null=True)),
                ('artigo', models.CharField(max_length=256, null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('preco_total', models.FloatField(null=True)),
                ('data_emissao_fatura', models.DateField(null=True)),
                ('encomenda_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.encomendacliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(max_length=256, null=True)),
                ('morada_fornecedor', models.CharField(max_length=256, null=True)),
                ('nif', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=256, null=True)),
                ('morada_funcionario', models.CharField(max_length=256, null=True)),
                ('telemovel_funcionario', models.IntegerField(null=True)),
                ('idade', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaDeRemessa',
            fields=[
                ('id_guia_de_remessa', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.CharField(max_length=256, null=True)),
                ('nif_destinatario', models.IntegerField(null=True)),
                ('data_saida_forn', models.DateField(null=True)),
                ('nome_produto', models.CharField(max_length=256, null=True)),
                ('quantidade_produto', models.IntegerField(null=True)),
                ('peso_produto', models.FloatField(null=True)),
                ('encomenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.encomendacliente')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='StockComponente',
            fields=[
                ('id_stock', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(null=True)),
                ('preco_stock', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id_tipo_componente', models.IntegerField(primary_key=True, serialize=False)),
                ('designacao_tipo_componente', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEquipamento',
            fields=[
                ('id_tipo_de_equipamento', models.IntegerField(primary_key=True, serialize=False)),
                ('designacao_tipo_de_equipamento', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUtilizador',
            fields=[
                ('id_tipo_utilizador', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_utilizador', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id_utilizador', models.AutoField(primary_key=True, serialize=False)),
                ('morada_utilizador', models.CharField(max_length=256, null=True)),
                ('nome', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('telemovel', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('NIF', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('encomenda_utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.encomendacliente')),
                ('fatura_utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.faturacliente')),
                ('tipo_utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.tipoutilizador')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeMaoDeObra',
            fields=[
                ('id_tipo_mao_de_obra', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao_tipo_mao_de_obra', models.CharField(max_length=256, null=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id_producao', models.AutoField(primary_key=True, serialize=False)),
                ('horas_producao', models.FloatField(null=True)),
                ('custos', models.FloatField(null=True)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.componente')),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='PCBusca_ProjetoApp.equipamento')),
                ('tipo_mao_de_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.tipodemaodeobra')),
            ],
        ),
        migrations.CreateModel(
            name='NotasDeEncomenda',
            fields=[
                ('encomenda', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_encomenda', models.CharField(max_length=256, null=True)),
                ('morada_fornecedor', models.CharField(max_length=256, null=True)),
                ('valor_total', models.FloatField(null=True)),
                ('data_de_envio', models.DateField(null=True)),
                ('data_de_chegada', models.DateField(null=True)),
                ('guia_de_remessa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.guiaderemessa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacoesDeStock',
            fields=[
                ('id_movimentacao_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(null=True)),
                ('fatura_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.faturacliente')),
                ('guia_de_remessa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.guiaderemessa')),
                ('producao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.producao')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaDeFatura',
            fields=[
                ('id_linha_de_fatura', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=256, null=True)),
                ('designacao_de_artigo', models.CharField(max_length=256, null=True)),
                ('preco_unitario', models.FloatField(null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('preco_total', models.FloatField(null=True)),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.equipamento')),
                ('fatura_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.faturacliente')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaDeEncomenda',
            fields=[
                ('id_linha_de_encomenda', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=256, null=True)),
                ('designacao_de_artigo', models.CharField(max_length=256, null=True)),
                ('preco_unitario', models.FloatField(null=True)),
                ('quantidade_encomendada', models.IntegerField(null=True)),
                ('preco_total', models.FloatField(null=True)),
                ('encomenda_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.encomendacliente')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='producao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='PCBusca_ProjetoApp.producao'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.tipodeequipamento'),
        ),
        migrations.CreateModel(
            name='EncomendaComponente',
            fields=[
                ('id_encomenda_componente', models.AutoField(primary_key=True, serialize=False)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.componente')),
                ('encomenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.encomendacliente')),
            ],
        ),
        migrations.AddField(
            model_name='encomendacliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.utilizador'),
        ),
        migrations.AddField(
            model_name='encomendacliente',
            name='equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.equipamento'),
        ),
        migrations.AddField(
            model_name='componente',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.fornecedor'),
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo_componente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.tipocomponente'),
        ),
        migrations.CreateModel(
            name='Producao2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCBusca_ProjetoApp.componente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCBusca_ProjetoApp.equipamento')),
            ],
            options={
                'unique_together': {('equipamento', 'componente')},
            },
        ),
    ]
