# Generated by Django 4.1.3 on 2023-12-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0004_utilizador_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='encomenda_utilizador',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='fatura_utilizador',
        ),
    ]
