# Generated by Django 4.1.3 on 2023-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0005_remove_utilizador_encomenda_utilizador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
