# Generated by Django 4.1.3 on 2023-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0007_utilizador_data_desativado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email_fornecedor',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telemovel_fornecedor',
            field=models.IntegerField(null=True),
        ),
    ]
