# Generated by Adriano Valente do Vale on 2024-01-14 18:42

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0010_alter_stockcomponente_id_stock_and_more'),
    ]

    operations = [
        #migrations.RemoveField('Equipamento','producao')
    ]
