# Generated by Django 4.1.3 on 2024-01-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0011_auto_20240114_1842'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipamento',
        #     name='nome_equipamento',
        #     field=models.CharField(max_length=256, null=True),
        # ),
    ]
