# Generated by Django 4.1.3 on 2024-02-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCBusca_ProjetoApp', '0016_carrinho_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Carrinho',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('utilizador_id', models.IntegerField()),
        #         ('equipamento_id', models.IntegerField()),
        #         ('quantidade', models.IntegerField()),
        #     ],
        # ),
        # migrations.RemoveField(
        #     model_name='equipamento',
        #     name='componente',
        # ),
        # migrations.RemoveField(
        #     model_name='equipamento',
        #     name='producao',
        # ),
        # migrations.RemoveField(
        #     model_name='producao',
        #     name='componente',
        # ),
        # migrations.RemoveField(
        #     model_name='tipodemaodeobra',
        #     name='funcionario',
        # ),
        migrations.AddField(
            model_name='equipamento',
            name='imagem_equip',
            field=models.ImageField(blank=True, null=True, upload_to='equip_images/'),
        ),
        # migrations.AddField(
        #     model_name='equipamento',
        #     name='nome_equipamento',
        #     field=models.CharField(max_length=256, null=True),
        # ),
        # migrations.AddField(
        #     model_name='funcionarios',
        #     name='TipoDeMaoDeObra_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PCBusca_ProjetoApp.tipodemaodeobra'),
        # ),
        # migrations.AlterField(
        #     model_name='equipamento',
        #     name='stock_min_equip',
        #     field=models.IntegerField(),
        # ),
        # migrations.AlterField(
        #     model_name='stockcomponente',
        #     name='id_stock',
        #     field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='tipocomponente',
        #     name='id_tipo_componente',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='tipodeequipamento',
        #     name='id_tipo_de_equipamento',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='tipodemaodeobra',
        #     name='id_tipo_mao_de_obra',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
